on:
  push:
    branches:
      - "**"
    tags:
      - "*.*.*"
    paths-ignore:
      - "README.md"

  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-20.04, macos-12 ]

    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - name: Setup net5.0
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: "5.0.408"

      - name: Setup net6.0
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: "6.0.403"

      - name: Setup net7.0
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: "7.0.101"

      - name: Cache Tools
        uses: actions/cache@v2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: Build project
        uses: cake-build/cake-action@v1
        with:
          script-path: recipe.cake
          target: CI
          verbosity: Normal
          cake-version: 1.3.0
          cake-bootstrap: false

      - name: Upload Issues-Report
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: issues
          path: BuildArtifacts/report.html

      - name: Upload Packages
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*
